"""
LLM Behavioral Insights — per-person spending analysis and priority actions.
"""
from __future__ import annotations
import os
import sys
from pathlib import Path
import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.config import DATA_DIR, PEOPLE, EXCLUDE_FROM_LIFESTYLE
from src.parsers import load_person_data
from src.categoriser import get_spending_df
from src.forecaster import prepare_monthly_series, run_all_forecasts
from src.llm_insights import GROQ_AVAILABLE, generate_insights
from src.supabase_store import invalidate_cache, is_available as sb_available
from src.overrides_store import load_overrides

st.set_page_config(page_title="Insights", page_icon="💡", layout="wide")
st.title("💡 Behavioral insights & priority actions")
st.caption("LLM-generated spending analysis with RAG caching — powered by Groq")


@st.cache_data(show_spinner="Loading data…")
def load_all(d: str) -> dict:
    result = {}
    for p in PEOPLE:
        bank, cc = load_person_data(p, Path(d))
        result[p] = get_spending_df(bank, cc)
    return result


all_data = load_all(str(DATA_DIR))

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Settings")
    person = st.selectbox("Person", PEOPLE)

    # API key — always blank in UI (BUG security fix)
    secret_key = ""
    try:
        secret_key = st.secrets.get("GROQ_API_KEY", "")
    except Exception:
        secret_key = os.environ.get("GROQ_API_KEY", "")
    api_key_input = st.text_input(
        "Groq API key", value="", type="password",
        placeholder="gsk_... (leave blank to use server key)",
    )
    api_key = api_key_input.strip() or secret_key

    model = st.selectbox("Model",
        ["llama-3.3-70b-versatile", "llama3-8b-8192"])

    st.divider()
    df = all_data[person]
    if not df.empty:
        avail_cats = sorted(df["Category"].unique().tolist())
        # BUG-1 fix
        safe_exc     = [c for c in EXCLUDE_FROM_LIFESTYLE if c in avail_cats]
        exclude_cats = st.multiselect("Exclude categories", avail_cats, default=safe_exc)
    else:
        exclude_cats = list(EXCLUDE_FROM_LIFESTYLE)

    st.divider()
    st.header("Cache")
    cache_days = st.slider("Report TTL (days)", 1, 30, 7)
    force_refresh = st.checkbox("Force regenerate", value=False,
                                 help="Ignore cache and call Groq even if a recent report exists")
    if st.button("🗑 Invalidate cache", help="Delete all cached reports for this person"):
        invalidate_cache(person)
        st.toast(f"Cache cleared for {person}", icon="🗑️")

    st.divider()
    if sb_available():
        st.success("Supabase connected", icon="✅")
    else:
        st.info("Supabase not configured — cache uses local session only.", icon="ℹ️")

# ── Main ──────────────────────────────────────────────────────────────────────
df = all_data[person]
if df.empty:
    st.warning(f"No data loaded for {person}.")
    st.stop()

if not GROQ_AVAILABLE:
    st.error("groq package not installed. Run: `pip install groq`", icon="❌")
    st.stop()

if not api_key:
    st.warning("Enter a Groq API key in the sidebar to generate insights.", icon="⚠️")
    st.stop()

# Filter data
filtered = df[~df["Category"].isin(exclude_cats)]
series   = prepare_monthly_series(filtered, clip=True)

if len(series) < 2:
    st.warning("Need at least 2 months of data to generate insights.")
    st.stop()

# Load goals from Supabase
goals: dict = {}
try:
    from src.supabase_store import fetch_goals
    goals = fetch_goals(person) or {}
except Exception:
    pass

# Compute forecasts for prompt context (lightweight — runs fast)
forecasts = run_all_forecasts(series, n_months=3)

# ── Generate report ───────────────────────────────────────────────────────────
with st.spinner("Generating insights…"):
    report, from_cache = generate_insights(
        person=person,
        spending_df=filtered,
        series=series,
        forecasts=forecasts,
        goals=goals,
        api_key=api_key,
        model=model,
        force_refresh=force_refresh,
        max_age_days=cache_days,
    )

# ── Status banner ─────────────────────────────────────────────────────────────
if from_cache:
    st.info("Loaded from cache — click 'Force regenerate' or clear cache to refresh.", icon="⚡")
else:
    st.success("Report generated by Groq LLM.", icon="✅")

# ── Render report ─────────────────────────────────────────────────────────────
st.markdown("---")

# Context card
n_months = series.nunique()
lifestyle = filtered[~filtered["Category"].isin(EXCLUDE_FROM_LIFESTYLE)]
total = lifestyle["Amount"].sum()
avg   = total / n_months if n_months else 0

kc1, kc2, kc3, kc4 = st.columns(4)
kc1.metric("Total (period)", f"฿{total:,.0f}")
kc2.metric("Avg / month",    f"฿{avg:,.0f}")
kc3.metric("Months analysed", n_months)
if goals.get("monthly_savings_target"):
    gap = avg - float(goals["monthly_savings_target"])
    kc4.metric("Goal gap / mo",
               f"฿{abs(gap):,.0f}",
               delta="over target" if gap > 0 else "under target ✓",
               delta_color="inverse" if gap > 0 else "normal")

st.markdown("---")

# Render the markdown report
st.markdown(report)

# ── Action items extracted as cards ──────────────────────────────────────────
st.markdown("---")
st.subheader("Quick reference — priority actions")

# Parse action items from report (simple extraction)
action_lines = []
in_actions = False
for line in report.splitlines():
    if "## Priority actions" in line or "## priority action" in line.lower():
        in_actions = True
        continue
    if in_actions:
        if line.startswith("## "):
            break
        if line.strip().startswith(("- ", "* ", "1.", "2.", "3.", "4.", "5.")):
            clean = line.lstrip("0123456789.- *").strip()
            if clean:
                action_lines.append(clean)

if action_lines:
    cols = st.columns(min(len(action_lines), 3))
    for i, action in enumerate(action_lines[:6]):
        with cols[i % len(cols)]:
            st.markdown(
                f'<div style="border:0.5px solid var(--color-border-tertiary);'
                f'border-radius:8px;padding:12px 14px;font-size:13px;'
                f'color:var(--color-text-secondary);line-height:1.5">'
                f'{action}</div>',
                unsafe_allow_html=True,
            )
else:
    st.caption("Priority actions will appear here once the report is parsed.")

# ── Download ──────────────────────────────────────────────────────────────────
st.markdown("---")
st.download_button(
    "⬇ Download report (Markdown)",
    report.encode("utf-8"),
    f"{person}_insights.md",
    "text/markdown",
)
